### ISSUE TITLE
Merge parallel edges for PyMatching

### ISSUE THREAD

**Issue by oscarhiggott** [Strilanc/honeycomb_threshold#4]
The stim detector error model (DEM) format can have multiple error mechanisms with the same targets, however neither `networkx.Graph` nor PyMatching support parallel edges. When a duplicate edge is added to a `networkx.Graph`, the old edge data is silently replaced with the new edge data. To workaround this problem, parallel edges should be merged when converting a DEM to a `pymatching.Matching` object.

One solution is to change the `handle_error` function in decoder.py. i.e. it could be changed from
```
    def handle_error(p: float, dets: List[int], frame_changes: List[int]):
        if p == 0:
            return
        if len(dets) == 1:
            dets.append(num_detectors)
        if len(dets) != 2:
            return  # Just ignore correlated error mechanisms (e.g. Y errors / XX errors)
        g.add_edge(*dets, weight=-math.log(p), qubit_id=frame_changes)
```

to

```
    def handle_error(p: float, dets: List[int], frame_changes: List[int]):
        if p == 0:
            return
        if len(dets) == 1:
            dets.append(num_detectors)
        if len(dets) != 2:
            return  # Just ignore correlated error mechanisms (e.g. Y errors / XX errors)
        if g.has_edge(*dets):
            edge_data = g.get_edge_data(*dets)
            old_p = edge_data["error_probability"]
            old_frame_changes = edge_data["qubit_id"]
            if set(old_frame_changes) != set(frame_changes):
                raise NotImplementedError()
            p = p * (1 - old_p) + old_p * (1 - p)
            g.remove_edge(*dets)
        g.add_edge(*dets, weight=math.log((1-p)/p), qubit_id=frame_changes, error_probability=p)
```
(Note that I use log((1-p)/p) for weights, but maybe you prefer to keep -log(p) instead).

In the next PyMatching release, I'll add support to add edges directly to `pymatching.Matching` rather than relying on NetworkX, and either raise an exception when a parallel edge is added or merge it internally.

**Comment by Strilanc** [comment]
Good catch!

I should probably also make it merge the components of suggested-decomposition errors while I'm at it.
